name: Check commit conventions

on:
  pull_request:
  workflow_call:
    inputs:
      GH_TOKEN:
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-commitlint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: ./.github/setup

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: pnpm dlx commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: pnpm dlx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
