name: Format and lint

on:
  pull_request:
  workflow_call:
    inputs:
      GH_TOKEN:
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/setup

      - name: Run lint
        run: pnpm lint

      - name: Run format
        run: pnpm format
