name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  commitlint:
    name: Check commit conventions
    uses: ./.github/workflows/commitlint.yaml

  format:
    name: Format and lint
    uses: ./.github/workflows/format.yaml

  test:
    name: Test
    uses: ./.github/workflows/test.yaml
    permissions:
      contents: read
      pull-requests: write

  release:
    needs: [commitlint, format, test]
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup environment
        uses: ./.github/setup

      - name: Disable Husky in CI
        run: echo "HUSKY=0" >> $GITHUB_ENV

      - name: Publish package
        uses: cycjimmy/semantic-release-action@v4
        with:
          working_directory: ./packages/core
          semantic_version: latest
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/commit-analyzer
            @semantic-release/git
            @semantic-release/github
            @semantic-release/npm
            @semantic-release/release-notes-generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
